Robot:
  Hero:
    length: 0.5
    width: 0.4
    armor_count: 4
    high_height: 0.15
    low_height: 0.1
    armor_size: large
    light_bar_interval: 0.23
    light_bar_length: 0.055

  Infantry:
    length: 0.5
    width: 0.4
    armor_count: 4
    high_height: 0.15
    low_height: 0.1
    armor_size: small
    light_bar_interval: 0.135
    light_bar_length: 0.055

  Sentry:
    length: 0.5
    width: 0.4
    armor_count: 2
    high_height: 0.0
    low_height: 0.1
    armor_size: small
    light_bar_interval: 0.135
    light_bar_length: 0.055

  Engineer:
    length: 0.5
    width: 0.4
    armor_count: 4
    high_height: 0.15
    low_height: 0.1
    armor_size: small
    light_bar_interval: 0.135
    light_bar_length: 0.055